//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hrithvika.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hrithvik_preyuvanirman
    {
        public int id { get; set; }
        public string NAME { get; set; }
        public string Father_name { get; set; }
        public string email { get; set; }
        public string Address { get; set; }
        public string phone { get; set; }
        public string category { get; set; }
        public string institution_name { get; set; }
        public string institution_address { get; set; }
        public string project_title { get; set; }
        public string project_description { get; set; }
        public Nullable<int> group_mumbers { get; set; }
        public string class_or_course { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public string Date_of_birth { get; set; }
    }
}
