//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hrithvika.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hrithvik_NGO
    {
        public int id { get; set; }
        public string orgname { get; set; }
        public string orgemail { get; set; }
        public System.DateTime createdon { get; set; }
        public string orgphone { get; set; }
        public string orglogo { get; set; }
        public string orgdocuments { get; set; }
        public string orgaddress { get; set; }
        public string presidentname { get; set; }
        public string presedentphone { get; set; }
        public string secretaryname { get; set; }
        public string secretaryphone { get; set; }
        public string presidentemail { get; set; }
        public string secretaryemail { get; set; }
        public string State { get; set; }
        public string teamtype { get; set; }
    }
}
