//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hrithvika.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hrithvik_yuvanirman
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public System.DateTime createdon { get; set; }
        public string phone { get; set; }
        public string organization { get; set; }
        public string about { get; set; }
        public string address { get; set; }
        public string awards { get; set; }
        public string email { get; set; }
        public string orglogo { get; set; }
        public string category { get; set; }
        public string video1 { get; set; }
        public string projectimages { get; set; }
        public string projectimages1 { get; set; }
        public string projectimages2 { get; set; }
        public string newsarticle1 { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public int isactive { get; set; }
    }
}
