//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hrithvika.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRTVIK_gallery
    {
        public int id { get; set; }
        public int eventid { get; set; }
        public string image_url { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public string createdby { get; set; }
        public string eventtype { get; set; }
        public Nullable<int> main_event { get; set; }
    }
}
