//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hrithvika.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRTVIK_OGalery
    {
        public int id { get; set; }
        public string path { get; set; }
        public System.DateTime createdon { get; set; }
        public string TYPE { get; set; }
        public bool isimportant { get; set; }
        public Nullable<int> rank { get; set; }
        public string title { get; set; }
        public string category { get; set; }
    }
}
