//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hrithvika.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ph16787236639_Entities : DbContext
    {
        public ph16787236639_Entities()
            : base("name=ph16787236639_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<Donation> Donations { get; set; }
        public virtual DbSet<Hrithvik_NGO> Hrithvik_NGO { get; set; }
        public virtual DbSet<Hrithvik_yuvanirman> Hrithvik_yuvanirman { get; set; }
        public virtual DbSet<HRTVIK_events> HRTVIK_events { get; set; }
        public virtual DbSet<HRTVIK_gallery> HRTVIK_gallery { get; set; }
        public virtual DbSet<HRTVIK_OGalery> HRTVIK_OGalery { get; set; }
        public virtual DbSet<HRTVIK_OurTeam> HRTVIK_OurTeam { get; set; }
        public virtual DbSet<Nomination_type> Nomination_type { get; set; }
        public virtual DbSet<Nomination> Nominations { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<Team_type> Team_type { get; set; }
    }
}
