//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hrithvika.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomination
    {
        public int id { get; set; }
        public string NAME { get; set; }
        public string title { get; set; }
        public string Description { get; set; }
        public string display_image { get; set; }
        public string video { get; set; }
        public int isactive { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> isdeleted { get; set; }
        public string category { get; set; }
    }
}
